-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "customFields" JSONB,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "dimensionHeight" DOUBLE PRECISION,
ADD COLUMN     "dimensionLength" DOUBLE PRECISION,
ADD COLUMN     "dimensionWidth" DOUBLE PRECISION,
ADD COLUMN     "gst" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "hsnSac" TEXT,
ADD COLUMN     "image" TEXT,
ADD COLUMN     "inventoryType" TEXT DEFAULT 'Finished Goods',
ADD COLUMN     "name" TEXT,
ADD COLUMN     "productTag" TEXT,
ADD COLUMN     "schemes" JSONB,
ADD COLUMN     "sellPrice" DOUBLE PRECISION,
ADD COLUMN     "variants" JSONB,
ALTER COLUMN "netWeight" DROP NOT NULL,
ALTER COLUMN "grossWeight" DROP NOT NULL;
